### ISSUE TITLE
Can't downgrade asus system control interface v3

### ISSUE THREAD

**Issue by Sadik-Sami** [Karmel0x/AsusFanControl#48]
I manually need to uninstall the driver and reboot everytime to use the fan control. I tried to installed the prior version but it says some features can not be used and it fails to install. I use asus x509dj

**Comment by kiranteqnos** [comment]
Same here. On Asus TUF F17 after windows update.

Edit:

Fixed my issue.
Go to device manager.
Find Asus System Control Interface V3
Go to its properties
Go to Driver tab and select Roll back driver

This rolled back my version to the previous one and everything is working fine now.

**Comment by Karmel0x** [comment]
[releases](https://github.com/Karmel0x/AsusFanControl/releases)
#40

**Comment by roRICK-ship-it** [comment]
Hi, I still can't uninstall the driver to install the previous version. I'm in a cycle. I did everything, and how do I uninstall it completely?

**Comment by roRICK-ship-it** [comment]
> Lo mismo me pasa. En el Asus TUF F17 después de actualizar Windows.
> 
> Editar:
> 
> Se solucionó mi problema. Ve al administrador de dispositivos. Busca Asus System Control Interface V3. Ve a sus propiedades. Ve a la pestaña Controlador y selecciona Revertir controlador.
> 
> Esto revirtió mi versión a la anterior y todo está funcionando bien ahora.

THAT OPTION IS DISABLED IN MY CASE
